require('dotenv').config();

/**
 * block67.config.js — Project configuration file
 *
 * This file is auto-generated by `block67 init`.
 * Edit it to match your project's contracts and network.
 */
module.exports = {
  // Target network: mainnet | sepolia | goerli | polygon | localhost
  network: "sepolia",

  // RPC endpoint — load from .env (recommended)
  rpcUrl: process.env.RPC_URL,

  // Deployer private key — loaded from .env (NEVER hard-code this)
  privateKey: process.env.PRIVATE_KEY,

  // Optional: set a global gas limit override
  // gasLimit: 3000000,

  contracts: {
    // Key = contract name (must match artifacts/<ContractName>.json)
    MyToken: {
      // Constructor arguments in order
      args: ["Test Token", "TT", 1000000]
    }
    // Add more contracts here:
    // NFTCollection: {
    //   args: ["My NFT", "MNFT"]
    // }
  }
};
