require('dotenv').config();

/**
 * block67.config.js — Project configuration
 * Generated by `block67 init`. Edit to match your project.
 */
module.exports = {
  // Active network — must match a key in the networks map below
  // Override at runtime: block67 deploy MyToken --network mainnet
  network: "sepolia",

  // Per-network RPC configuration
  // Use your own Alchemy / QuickNode / Infura keys.
  // block67 never proxies your requests — your key goes directly to the provider.
  networks: {
    sepolia: {
      rpcUrl: process.env.SEPOLIA_RPC_URL || process.env.RPC_URL,
      chainId: 11155111,
    },
    mainnet: {
      rpcUrl: process.env.MAINNET_RPC_URL,
      chainId: 1,
    },
    localhost: {
      rpcUrl: "http://127.0.0.1:8545",
      chainId: 31337,
    },
    // polygon: {
    //   rpcUrl: process.env.POLYGON_RPC_URL,
    //   chainId: 137,
    // },
  },

  // Deployer wallet private key — loaded from .env (NEVER hard-code this)
  privateKey: process.env.PRIVATE_KEY,

  // Optional: global gas limit override
  // gasLimit: 3000000,

  contracts: {
    // Key = contract name = artifact filename: artifacts/<Name>.json
    MyToken: {
      args: ["Test Token", "TT", 1000000],
      // gasLimit: 2000000,  // per-contract override
    }
    // NFTCollection: {
    //   args: ["My NFT", "MNFT"]
    // }
  }
};
